### ISSUE TITLE
RJ45 Pinout

### ISSUE THREAD

**Issue by dorfmobil** [chrishrb/hoval-gateway#1]
Hi, thanks for your work! I own a Homevent FR251 with TopTronic E. Can you add the pinout of the RJ45 CAN connector to the readme? I am not sure if GND is on Pin 3, 7 or both. Thanks!

**Comment by chrishrb** [comment]
Hello,
the pinout of the  RJ45 CAN connector is the following:

1 - CAN-High
2 - CAN-Low
7 - GND

Hope this helps. In a few weaks I want to release a better tested and improved version of the CAN Gateway, there the README will be updated, too.
Have fun.
