### ISSUE TITLE
Device Typ/Id  für eine Hoval Wärmepumpenheizung

### ISSUE THREAD

**Issue by LudwigWen** [chrishrb/hoval-gateway#3]
Hallo, 
Python ist zwar nicht meine Liebling, aber lesen geht gerade noch.
wie bestimmt man den Device Typ & Id für meine Wärmepumpenheizung.
will eher mit einem ESP32/ESP8266 und einem Canbus-Modul unter C++ die Anlage auslesen ggf. steuern.
Bin selber Programmierer aber CANBUS Neuling.
Wie wäre ein Request für einen speziellen DatenPunkt aussehen?
Schaut ja sehr analog Modbus aus.

Danke schon mal vorab für deine Hilfe

https://github.com/coryjfowler/MCP_CAN_lib/blob/master/examples/CAN_send/CAN_send.ino

**Comment by chrishrb** [comment]
Hallo,
Device Id wird anfangs vom Installateur vergeben. Diese steht im HomeVent Bedienmodul auch drin, wenn du ein solches besitzt.
Der Device Typ ist von Hoval eine feste Zahl, beim auslesen vom Bus merkt man allerdings recht schnell, wie diese ist - genauso wie die device id.

Ein Datenpunkt sieht im Grunde so aus (siehe angehängte Grafik) Diese Grafik habe ich vor einem halben Jahr angefertigt & ist nur für Requests/Responses, die aus einer Nachricht bestehen, gültig.
Aber ich musste das meiste auch selber Reverse Engineeren - ich weiß deshalb hier auch nicht so viel. Einfach mal auslesen mit Candump.

![IMG_2329](https://user-images.githubusercontent.com/52382992/129340980-3d469f8f-d661-49fa-b0af-a942c63e5015.jpeg)


Kann dir zu dem Thema auch noch folgende Links empfehlen:
- https://github.com/wladwnt/CAN-Gateway
- https://github.com/zittix/Hoval-GW

Meine neue Implementierung, die noch nicht ganz funktionsfähig ist, siehst du unter dem Pull request - diese ist auch besser strukturiert, evtl. hilft dir das auch noch.

Viel Erfolg und Spaß noch.
Grüße Christoph
