### ISSUE TITLE
Homevent VOC / air quality control 

### ISSUE THREAD

**Issue by Zomkidom** [chrishrb/hoval-gateway#4]
Hi,

Is there a way to turn on/off the VOC functionality? Aka “air quality control”

Thank you!

**Comment by chrishrb** [comment]
Hi, 
do you have the topTronic operating module? Is it possible there to turn this off?

**Comment by Zomkidom** [comment]
Kind of.

It’s possible to turn it off completely (as in, turn off the functionality of “air quality control”), or turn it on.

However, even when turned on, I don’t see the current state as being “voc”, it stays on “normal”.

Unfortunately Hoval seems clueless and cannot themselves explain how it works.

**Comment by chrishrb** [comment]
This repository is only about controlling the hoval devices like from the TopTronic operating module. I don't know how VOC works, sorry.
