### ISSUE TITLE
TopTronic E

### ISSUE THREAD

**Issue by jostauber** [chrishrb/hoval-gateway#7]
Hi, thank you for your work! I have a HOVAL heat pump and I mounted a Raspberry in PICAN2. My question is as follows: do I have to connect the CAN wires coming out of the heat pump directly to the PICAN or can I use the RJ45 output of the HOVAL gateway that I already have? Another question: can you give me the exact command to launch the SCRIPT as it is written in your tutorial? I can't define which file to execute? Thank you 
Joël

**Comment by chrishrb** [comment]
Hi,
this gateway has nothing to do with the one from hoval. If you want to use this script, you have to connect it directly to the heat pump. BUT: I don't have a heat pump of hoval, i only have the ventilation system, so i don't know the datapoints.
You only have to clone the script, then install the requirements and execute it with the settings file (you first have to insert your correct datapoints and device settings!!) and the following command:

`python3 . -s settings.yml`

I recommend you to first dump some data from the device with the canutils and then read the file with the script "offline", so you can test your datapoints first. If your system does run, maybe you can make a pull request with the working settings file for the heat pump.

**Comment by pehon** [comment]
Hi Chrishrb!
What kind of ventilation system (and additional Hoval components) are you using?
I'm thinking about buying a "Hoval ER400", but I'm unsure which additional components I need to control it from a home automation system (or is a CAN bus already included?). TopTrinic E looks - for me - like an overkill (I don't need a fancy display).
Thanks

**Comment by markus2330** [comment]
Did you already asked Hoval if they give documentation of their bus? Which information do you have/which is missing? At the moment is a very good time to ask them: both the Hoval gateway and the TopTronic are not available, without any date when they again will be. So the "internal" Hoval bus is the only way to communicate with Hoval devices at the moment.

**Comment by chrishrb** [comment]
> Hi Chrishrb!
> 
> What kind of ventilation system (and additional Hoval components) are you using?
> 
> I'm thinking about buying a "Hoval ER400", but I'm unsure which additional components I need to control it from a home automation system (or is a CAN bus already included?). TopTrinic E looks - for me - like an overkill (I don't need a fancy display).
> 
> Thanks

Hello Pehon,
Im using the Hoval HomeVent FRT 251 and the TopTronic E. I programmed the Gateway afterwards - so the TopTronic was the first choice for me. 
The CAN Bus is already implemented, over this the TopTronic control component is communicating with the ventilation system. 

If you get your system to run, please let us know here.

**Comment by chrishrb** [comment]
> Did you already asked Hoval if they give documentation of their bus? Which information do you have/which is missing? At the moment is a very good time to ask them: both the Hoval gateway and the TopTronic are not available, without any date when they again will be. So the "internal" Hoval bus is the only way to communicate with Hoval devices at the moment.

Hello Markus, 
I think the main problem is, that I only have one ventilation system with which I can test this gateway. More documentation would be cool, then maybe new features (like alerting etc.) would be easier to implement. Which features do you think are still missing? Do you actively use this gateway?

Greetings Chris

**Comment by pehon** [comment]
Hello!
I'm using a Hoval ER400 with ESP32 CAN-Gateway from wled.shop. Sensor data and control with MQTT (and in my case iobroker) works perfect. The CAN Gateway is powered directly from HomeVent and the setup was easy (the “Standard Bediengerät” BG02E is disconnected and only here to not confuse the service technician). A TopTronic E would be useless in my case.
The CAN BUS datapoints are documented here:
http://www.hoval.com/misc/TTE/TTE-GW-Modbus-datapoints.xlsx

I'm using this datapoints:
param=8;8;0;0;21058;r;Restlaufzeit_Wartungszaehler_Wochen;10;U32;1;0;
param=8;8;50;0;0;r;Temperatur_Aussenluft_gradC;10;S16;0.1;0;
param=8;8;50;0;2010;w;Party_Modus_Restzeit_h;10;U16;0.1;0;
param=8;8;50;0;37600;r;Feuchtigkeit_Abluft_percent;10;U8;1;0;
param=8;8;50;0;37602;r;Temperatur_Abluft_gradC;10;S16;0.1;0;
param=8;8;50;0;38600;r;Ventilator_Fortluft_soll_percent;10;U8;1;0;
param=8;8;50;0;38606;r;Lueftungsmodulation_percent;10;U8;1;0;
param=8;8;50;0;39600;w;Luftqualitaet_Regulierung;10;U8;1;0;
param=8;8;50;0;39652;r;Status_Lueftungsregelung;10;U8;1;0;
param=8;8;50;0;40650;w;Betriebswahl_Lueftung;10;U8;1;0;
param=8;8;50;0;40651;w;Normal_Lueftungsmodulation_percent;10;U8;1;0;
param=8;8;50;0;40686;w;Spar_Lueftungsmodulation_percent;10;U8;1;0;
param=8;8;50;0;40687;w;Feuchte_Sollwert_percent;10;U8;1;0;

Thanks,
Peter

**Comment by chrishrb** [comment]
So are you using this software or the one from wladwnt? Or how did you managed to execute this Python script on an esp microcontroller?

Greetings Chris

**Comment by pehon** [comment]
sorry to not mention this, I'm using the software from wladwnt.

**Comment by markus2330** [comment]
Thank you for your reply @chrishrb!

> http://www.hoval.com/misc/TTE/TTE-GW-Modbus-datapoints.xlsx

Are these datapoints also for the internal bus or are they only for the gateway from Hoval?

> I think the main problem is, that I only have one ventilation system with which I can test this gateway. More documentation would be cool, then maybe new features (like alerting etc.) would be easier to implement.

Did you ask Hoval? I can also send them a general request but you know much more which information you would need.

Btw. Hoval said to me that their internal bus is simply "2 transmission lines with 24V", they did not even confirm that they use CAN.

Do I understand correctly that [hoval-gateway](https://github.com/chrishrb/hoval-gateway) can be connected in the same way as TopTronic E RaumbedienModul is connected?

> Which features do you think are still missing?

I didn't check yet. But as I have a totally different Hoval device (a heating pump), I assume I'll need to invest quite some time until anything works? Did you implement some feature to auto-detect a device and list datapoints it offers?

> Do you actively use this gateway?

My plan is to collect the data my heating pump offers in [Nextcloud Analytics](https://apps.nextcloud.com/apps/analytics). I don't know yet if I can directly use this gateway or if I need to do a reimplementation.

Many greetings from Austria!

**Comment by markus2330** [comment]
Any update here? Can I assume http://www.hoval.com/misc/TTE/TTE-GW-Modbus-datapoints.xlsx does not apply and nobody asked?

**Comment by kxn25** [comment]
I cant open this Modbus xlsx file!
Where else can i get it?
does anyone have this system with a Hoval TTE-WEZ?

**Comment by pehon** [comment]
I've just checked, download directly from hoval.com is working without any issue.

**Comment by chrishrb** [comment]
i assume that this issue can be closed? or are there any open issues left here?

**Comment by markus2330** [comment]
I don't know about the initial issue. I didn't get an answer if there is documentation from Hoval missing which requires to do reverse engineering.

**Comment by chrishrb** [comment]
yes, not everything is documented in the excel that you mentioned (or i didn‘t understand it 😄 ). I also know that this script isn‘t nearly perfekt because its designed only for my specific ventilation system. Maybe if I have the time and the motivation I will rewrite this script in rust and add some features to make it more general

**Comment by chrishrb** [comment]
I close this issue because there wasn't any activity in the past 4 months. If you still have questions or problems, please create a new issue! 👍
