### ISSUE TITLE
Feature Request: Home Assistant addon

### ISSUE THREAD

**Issue by CDaxi** [chrishrb/hoval-gateway#8]
Hello,

could you provide this repo as a home assistant addon to be installed on the HA machine directly and be configured via the UI?
This will make an additional raspberry pi or machine where the docker image is running obsolete.
It would be a great advantage for HA users.

Thanks a lot.
CDaxi

**Comment by chrishrb** [comment]
Hello, 
this is not generally possible because you need the connection to the hoval machine over the CAN bus on the machine that runs HA. I don‘t think that this is the case for most users (including me).

Greetings Christoph

**Comment by bagges** [comment]
I agree with @chrishrb.

It would be cool to port the code to something like ESPHOME. Then we would just need an ESP32 instead of a raspberry pi. Also the integration in Home Assistant would then be easy. I have this on my list, but did not start with it yet because the raspberry pi solution runs too stable :-D

**Comment by chrishrb** [comment]
haha same here. I wanted to rewrite the code in rust so I can run it on a microcontroller but i was too lazy (and there was not really a reason for it). Maybe in the next semester break 😄

**Comment by bagges** [comment]
I just started designing a PCB. 2x RJ45, CJMCU-230 (CAN Tranceiver), ESP32 Dev Kit v4, DC/DC Step Down Converter... Are any of you interested?

**Comment by CDaxi** [comment]
> I just started designing a PCB. 2x RJ45, CJMCU-230 (CAN Tranceiver), ESP32 Dev Kit v4, DC/DC Step Down Converter... Are any of you interested?

Yes I am. Do you plan to implement it with ESPHome? Thats currently my preferred solution if a HA addon will not be available and read already the esphome docs about canbus and ordered some boards to create some tests. Currently I have no Hoval HV but could be the choice in near future.

**Comment by nliaudat** [comment]
> I just started designing a PCB. 2x RJ45, CJMCU-230 (CAN Tranceiver), ESP32 Dev Kit v4, DC/DC Step Down Converter... Are any of you interested?

Me too, perhaps https://github.com/MagnusThome/RejsaCAN-ESP32 could help.

**Comment by bagges** [comment]
![pcb_esp32_canbus](https://github.com/chrishrb/hoval-gateway/assets/2102004/82eac234-3606-4afd-ae41-aa6239a691ea)

![schematic_esp32_canbus](https://github.com/chrishrb/hoval-gateway/assets/2102004/2ca77069-b684-46ae-aa04-6e0ff06a49d8)

This is what I created, but I had no time to test the PCB yet. I have 4 spare PCBs if someone is interessted...

**Comment by nliaudat** [comment]
Can you share the easyeda project or source ? 
(I mean the hoval can-bus power is 12V)
I'll post the full modbus-datapoints from hoval in PR

**Comment by nliaudat** [comment]
That version seems to works, at it's sold for 50€ https://raw.githubusercontent.com/wladwnt/CAN-Gateway/master/KiCAD/Version5/CANGateway.svg (but the software cost 130€). 

![SVG Picture created as CANGateway](https://github.com/chrishrb/hoval-gateway/assets/6782613/540cc9c2-000d-48df-9dc2-779c351ba4e7)

**Comment by bagges** [comment]
I know this project but I do not like closed source projects. Also the PCB is too expensive for what I need.

The DC/DC converter has an input range of 7-24v.

I'll check how I can share the easyeda project.

**Comment by nliaudat** [comment]
Another project : https://github.com/MagnusThome/RejsaCAN-ESP32/blob/main/Schematics/Schematic_RejsaCAN%20v3.4.png

**Comment by nliaudat** [comment]
> This is what I created, but I had no time to test the PCB yet. I have 4 spare PCBs if someone is interessted...

Perhaps can you create a dedicated project on github ? I am not bad with esphome and electronics.
I propose to add an optional [BLE0939 power sensor](https://esphome.io/components/sensor/bl0939.html?highlight=power) and an optional relay to turn off power

**Comment by bagges** [comment]
Why would you need relais and power sensor?

**Comment by nliaudat** [comment]
> Why would you need relais and power sensor?

I have energy monitor in hassio and the relay is for fully stop the hvac. The minimum default runs at 15%

**Comment by nliaudat** [comment]
> The DC/DC converter has an input range of 7-24v.
What is the DC/DC module you use ? 

I like AMS1117-5.0

**Comment by bagges** [comment]
> > The DC/DC converter has an input range of 7-24v.
> > What is the DC/DC module you use ?
> 
> I like AMS1117-5.0

I do not know the chip on the module. "PEMENOL DC DC Step Down Modul"

**Comment by nliaudat** [comment]
> > > The DC/DC converter has an input range of 7-24v.
> > > What is the DC/DC module you use ?
> > 
> > 
> > I like AMS1117-5.0
> 
> I do not know the chip on the module. "PEMENOL DC DC Step Down Modul"

But your is ?

**Comment by nliaudat** [comment]
The shield is done : https://github.com/nliaudat/esp_canbus
Next the firmware part ....

**Comment by bagges** [comment]
Wow that looks nice!

**Comment by bagges** [comment]
@chrishrb could you maybe also help here? We are confused about the can_id's to use.

https://github.com/nliaudat/esp_canbus/issues/2

**Comment by chrishrb** [comment]
I think we can close this issue because @nliaudat created a separate project for this use case. For questions please look at this [repository](https://github.com/nliaudat/esp_canbus/issues/2).
