### ISSUE TITLE
not an issue : canbus hardware suggestion

### ISSUE THREAD

**Issue by nliaudat** [chrishrb/hoval-gateway#9]
https://www.waveshare.com/2-ch-can-hat.htm

half the price of PICAN2.

For that board : 
sudo nano /boot/config.txt
```

dtparam=spi=on
dtoverlay=mcp2515-can1,oscillator=16000000,interrupt=25
dtoverlay=mcp2515-can0,oscillator=16000000,interrupt=23
dtoverlay=spi-bcm2835-overlay
```

all informations on https://www.waveshare.com/wiki/2-CH_CAN_HAT
That board works with your code.

**Comment by chrishrb** [comment]
can be closed because of #10
